language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.0
  - 2.1.0
  - 2.1
  - 2.2.0
  - 2.2
  - 2.3.0
  - 2.3
  - 2.4.0
  - 2.4
  - 2.5.0
  - 2.5
  - 2.6.0
  - 2.6
before_install:
  - gem update bundler
script: bundle exec rspec
