---

on:
  schedule:
    - cron:                             "0 0 * * *"
  workflow_dispatch:                    {}

name:                                   "Issue Locking"
jobs:
  lock-issues:
    runs-on:                            "ubuntu-latest"
    steps:
      - name:                           "Lock Issues"
        uses:                           "dessant/lock-threads@v2"
        with:
          github-token:                 "${{ secrets.GITHUB_TOKEN }}"
          issue-lock-inactive-days:     "180"
          issue-exclude-created-before: ""
          issue-exclude-labels:         "outdated,on-hold,in-progress,watchlist"
          issue-lock-labels:            "outdated"
          issue-lock-comment:           >
            This issue has been automatically locked since there has not been
            any recent activity after it was closed.  Please open a new issue
            for related bugs.
          issue-lock-reason:            "resolved"
          process-only:                 "issues"

  lock-pull-requests:
    runs-on:                            "ubuntu-latest"
    steps:
      - name:                           "Lock Pull Requests"
        uses:                           "dessant/lock-threads@v2"
        with:
          github-token:                 "${{ secrets.GITHUB_TOKEN }}"
          pr-lock-inactive-days:        "180"
          pr-exclude-created-before:    ""
          pr-exclude-labels:            "outdated,on-hold,in-progress,watchlist"
          pr-lock-labels:               "outdated"
          pr-lock-comment:              >
            This issue has been automatically locked since there has not been
            any recent activity after it was closed.  Please open a new issue
            for related bugs.
          pr-lock-reason:               "resolved"
          process-only:                 "prs"
